### ISSUE TITLE
SetFilters does not refresh the current frame.

### ISSUE THREAD

**Issue by wenbingzhang** [valbok/QtAVPlayer#436]
When paused, setting a new filter will not refresh the current frame.

**Comment by wenbingzhang** [comment]
>> filters <<"astats=metadata=1:reset=1"<< "delogo=x=20:y=20:w=200:h=200";
    p.setFilters(filters);

There will be two frames, one of which has no filter applied.

**Comment by valbok** [comment]
Hi, thanks for contributing.
Setting new filter does not trigger updating a frame. It is intentionally made only for play(), pause() if not paused, stepBackward(), stepForward()

It is done like this, because current frame before new filter, is already processed and sent, and it is unable to reapply the filter on the same frame, since filters might be complicated too and expect many frames in sequence.
