### ISSUE TITLE
BUG - Função Stop

### ISSUE THREAD

**Issue by mxnt10** [valbok/QtAVPlayer#474]
A função stop não está parando a reprodução, está pausando a reprodulção.

Ao apertar stop eu presumo que ele deveria emitir o QAVPlayer::EndOfMedia e não emite.

Mas nesse caso, ao apertar o botão stop eu prefiro um QAVPlayer::MediaStop que pra mim ficaria melhor.

**Comment by valbok** [comment]
Hi, thanks for contribution!
`stop()` is made based on legacy from QMediaPlayer and many others, where it did not reset and or change the source.
So it just stops the playback, but does not close decoders, or seeks to end.
Opposite `pause()` which is supposed to send only one frame, `stop()` just stops without sending any frames. But emits also `StoppedState`, but not `EndOfMedia` because it did not reach the end.

**Comment by mxnt10** [comment]
vou ver o que eu posso fazer com o StoppedState
